name: testlinks
on:
  - push
  - pull_request

jobs:
  check_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Link check action
        uses: serega404/links-check-action@test3
        with:
          filePath: "README.md"
